INSERT INTO TRANSACTION (TRANSACTION_ID, TRANSACTION_AMOUNT, ACCOUNT_ID) VALUES (1, 1000000, 1);
INSERT INTO TRANSACTION (TRANSACTION_ID, TRANSACTION_AMOUNT, ACCOUNT_ID) VALUES (2, 2000000, 1);
INSERT INTO TRANSACTION (TRANSACTION_ID, TRANSACTION_AMOUNT, ACCOUNT_ID) VALUES (3, 4000000, 2);
INSERT INTO TRANSACTION (TRANSACTION_ID, TRANSACTION_AMOUNT, ACCOUNT_ID) VALUES (4, 3000000, 2);
INSERT INTO TRANSACTION (TRANSACTION_ID, TRANSACTION_AMOUNT, ACCOUNT_ID) VALUES (5, 5000000, 3);
INSERT INTO TRANSACTION (TRANSACTION_ID, TRANSACTION_AMOUNT, ACCOUNT_ID) VALUES (6, 6000000, 3);